# See also: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Project Tests
on:
  workflow_call: {}
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
      - '**.png'
permissions:
  contents: read
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - {"name": "Clean", "run:" "make clean"}
      - name: Bootstrap Cluster
        run: make bootstrap
      - name: Deploy Platforms/Apps
        run: make deploy
      - name: Smoke Tests
        run: make test
